/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanagementsystem;

/**
 *
 * @author Sazib
 */
public class EDIT extends javax.swing.JFrame {

    /**
     * Creates new form EDIT
     */
    public EDIT() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tableCOmbo = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        attributecombo = new javax.swing.JComboBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        values = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tableCOmbo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT..","Customer", "OrderList","OrderProduct", "Product","Supplier" }));
        tableCOmbo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tableCOmboActionPerformed(evt);
            }
        });
        getContentPane().add(tableCOmbo, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 200, 230, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementsystem/edit.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 380, 120, 30));

        attributecombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Loading.." }));
        attributecombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                attributecomboActionPerformed(evt);
            }
        });
        getContentPane().add(attributecombo, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 170, 30));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 210, 40));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 153, 153));
        jLabel2.setText("Value:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 290, -1, -1));
        getContentPane().add(values, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, 220, 40));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("EDIT:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 153, 153));
        jLabel4.setText("Provide ID you want to change:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementsystem/query bg.jpg"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
//tableCOmbo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "SELECT..","Customer", "OrderList","OrderProduct", "Product","Supplier","supplierbankaccountinfo","suppliercontactinfo" }));

    private void tableCOmboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tableCOmboActionPerformed
          String str = (String) tableCOmbo.getSelectedItem();
          if(str.equals("Customer")){
              attributecombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "customerId", "customerName", "customerHouseNo","customerRoadNo","customerCity","customerLocation","customerPhone","customerEmail" }));
          }else if(str.equals("OrderList")){
              attributecombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "orderId", "orderDate", "orderPayementType","totalAmountPayement" }));
          }else  if(str.equals("OrderProduct")){
              attributecombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "quantity", "totalPrice" }));
          }else  if(str.equals("Product")){
              attributecombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "productId", "productName","productStock","productPrice" }));
          }else  if(str.equals("Supplier")){
              attributecombo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "supplierId", "supplierName" }));
          }
    }//GEN-LAST:event_tableCOmboActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
           DBConnect db=new DBConnect();
           db.edit((String)tableCOmbo.getSelectedItem(), (String)attributecombo.getSelectedItem(), values.getText(), jTextField1.getText());


// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void attributecomboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_attributecomboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_attributecomboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EDIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EDIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EDIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EDIT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EDIT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox attributecombo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JComboBox tableCOmbo;
    private javax.swing.JTextField values;
    // End of variables declaration//GEN-END:variables
}
