/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanagementsystem;

import javax.swing.JOptionPane;

/**
 *
 * @author Sazib
 */
public class InventoryManageMentSystem extends javax.swing.JFrame {

    /**
     * Creates new form InventoryManageMentSystem
     */
    public InventoryManageMentSystem() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        admin_login_name = new javax.swing.JTextField();
        login_button = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        admin_login_password = new javax.swing.JPasswordField();
        BG = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        admin_login_name.setText("local");
        getContentPane().add(admin_login_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 300, 190, 30));

        login_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementsystem/login button.png"))); // NOI18N
        login_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_buttonActionPerformed(evt);
            }
        });
        login_button.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                login_buttonKeyPressed(evt);
            }
        });
        getContentPane().add(login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 410, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementsystem/developed by.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 460, 300, 30));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementsystem/developerS.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 460, 30, 30));

        admin_login_password.setText("root");
        admin_login_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                admin_login_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(admin_login_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 362, 190, 30));

        BG.setDisplayedMnemonic('I');
        BG.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementsystem/bg.jpg"))); // NOI18N
        getContentPane().add(BG, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void login_buttonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_login_buttonKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_buttonKeyPressed

    private void login_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_buttonActionPerformed
       String username=admin_login_name.getText();
       char passwords[]=admin_login_password.getPassword();
       String password="";
       for(int i=0; i<passwords.length;i++){
           password+=passwords[i];
       }
      System.out.println(password);
       DBConnect d=new DBConnect();
       String ans=d.adminLoginAccess(username, password);
        if(ans.equals("admin")) {
            Admin_display ad=new Admin_display();
            ad.setVisible(true);
            dispose();
        }else if(ans.equals("salesman")) {
            salesman_display sd=new salesman_display();
            sd.setVisible(true);
            dispose();
        }else {
            JOptionPane.showMessageDialog(null,"YOUR NAME OR PASSWORD IS NOT IN OUR DATABASE");
        }
        
        
// TODO add your handling code here:
    }//GEN-LAST:event_login_buttonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        craditsIntro c=new craditsIntro();
        c.setVisible(true);
        dispose();
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void admin_login_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_admin_login_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_admin_login_passwordActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
      // DBConnect db=new DBConnect();
       //db.getData();
     //  db.getDataQuery01();
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InventoryManageMentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InventoryManageMentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InventoryManageMentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InventoryManageMentSystem.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InventoryManageMentSystem().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BG;
    private javax.swing.JTextField admin_login_name;
    private javax.swing.JPasswordField admin_login_password;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton login_button;
    // End of variables declaration//GEN-END:variables
}
