/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventorymanagementsystem;

import java.util.Arrays;
import javax.swing.JComboBox;

/**
 *
 * @author Tahanima Chowdhury
 */
public class Query_Execute_Customer extends javax.swing.JFrame {

    /**
     * Creates new form Query_Execute_Customer
     */
    DBConnect db;
    public Query_Execute_Customer() {
        db = new DBConnect();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCustPurchase = new javax.swing.JLabel();
        btnGetId = new javax.swing.JButton();
        lblCustNum = new javax.swing.JLabel();
        btnGetTot = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCustPurchase.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCustPurchase.setForeground(new java.awt.Color(0, 153, 153));
        lblCustPurchase.setText("Details of a particular customer:");
        getContentPane().add(lblCustPurchase, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 220, 310, 30));

        btnGetId.setBackground(new java.awt.Color(0, 102, 102));
        btnGetId.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnGetId.setText("Get Information");
        btnGetId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetIdActionPerformed(evt);
            }
        });
        getContentPane().add(btnGetId, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 220, 140, 38));

        lblCustNum.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCustNum.setForeground(new java.awt.Color(0, 153, 153));
        lblCustNum.setText("Total number of customers till date: ");
        getContentPane().add(lblCustNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, -1, -1));

        btnGetTot.setBackground(new java.awt.Color(0, 102, 102));
        btnGetTot.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btnGetTot.setText("Get Total");
        btnGetTot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGetTotActionPerformed(evt);
            }
        });
        getContentPane().add(btnGetTot, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 330, 140, 30));

        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementsystem/back.png"))); // NOI18N
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        getContentPane().add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 440, 120, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 153, 153));
        jLabel1.setText("Details of all the customers:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 170, -1, -1));

        jButton1.setBackground(new java.awt.Color(0, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton1.setText("Get Information");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 170, 140, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(db.Combo(new String("customerId"),new String("customer"))));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 140, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 153));
        jLabel3.setText("Payment information of a particular customer:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 450, 40));

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel(db.Combo(new String("customerId"),new String("customer"))));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, 100, 30));

        jButton2.setBackground(new java.awt.Color(0, 102, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButton2.setText("Get Information");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 280, 150, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/inventorymanagementsystem/query bg.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
       Query_Form qF = new Query_Form(Query_Form.str);
       qF.setVisible(true);
       dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnGetTotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetTotActionPerformed
         db.getTotalCust();
    }//GEN-LAST:event_btnGetTotActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       db.getCustomerInfo();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
     String arr[] = db.Combo(new String("customerId"),new String("customer"));
     Arrays.sort(arr);
     jComboBox1.addItem(arr[0]);
     for(int i = 1; i<arr.length; i++){
       if(!arr[i].equals(arr[i-1])) jComboBox1.addItem(arr[i]);  
     }
     
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void btnGetIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGetIdActionPerformed
       db.getSpecificCustInfo((String)jComboBox1.getSelectedItem());
    }//GEN-LAST:event_btnGetIdActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        String arr[] = db.Combo(new String("customerId"),new String("customer"));
        Arrays.sort(arr);
        jComboBox2.addItem(arr[0]);
        for(int i = 1; i<arr.length; i++)
         if(!arr[i].equals(arr[i-1])) jComboBox2.addItem(arr[i]);
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        db.getSpecificCustPayType((String)jComboBox2.getSelectedItem());
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Query_Execute_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Query_Execute_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Query_Execute_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Query_Execute_Customer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Query_Execute_Customer().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnGetId;
    private javax.swing.JButton btnGetTot;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JComboBox jComboBox2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCustNum;
    private javax.swing.JLabel lblCustPurchase;
    // End of variables declaration//GEN-END:variables
}
